#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/cat \"aaa\r" }
  timeout { puts "Error: Did not receive prompt"; exit 1 }
}
expect {
  "`/cat` were parsed as a text" { send "/exit\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
