#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/clear \"in\"123/cp IN A\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  ">>> " { send "/cat A\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  "123\r" { send "/clear \"in\"abc/cp IN A/cat A\r" }
  timeout { puts "Error: Did not receive input 123"; exit 1 }
}
expect {
  "abc\r" { send "/exit\r" }
  timeout { puts "Error: Did not receive input abc"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
