#!/usr/bin/env expect-f.sh

set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/cd \"/\"\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  "Changing current directory to '/'" { send "/shell \"pwd\"\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  "/\r" { send "/exit\r" }
  timeout { puts "Error: Did not receive input 123"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
