#!/usr/bin/env expect-f.sh

set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "PROMPT /read model prompt\r" }
  timeout { puts "Error: Did not receive prompt"; exit 1 }
}

expect {
  "Setting actor prompt to 'PROMPT...'" { send "/exit\r" }
  timeout { puts "Error: Did not receive expected output"; exit 1 }
}

expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}

exit 0
