#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/set terminal rawbin true\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  "Setting terminal raw binary mode to 'True'\r" { }
  timeout { puts "Error: Did not receive input"; exit 1 }
}

expect {
  ">>> " { send "/set terminal rawbin no\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  "Setting terminal raw binary mode to 'False'\r" { send "/exit\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}

expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
