#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/set terminal prompt \"XXX \"\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  -re {'XXX '\r?\nXXX} { send "/set terminal prompt \"\"/echo YYY\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  -re {''\r?\nYYY} { send "/exit\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
