#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/shell \"echo 1; echo 2; exit 33\"\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  -re {1\r?\n2\r?\n.*code 33\r?\n} { send "/exit\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}
exit 0
