#!/usr/bin/env expect-f.sh

set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " {
    send "/set model temp 25.5\r"
  }
  timeout {
    puts "Error: Did not receive prompt"
    exit 1
  }
}

expect {
  "Setting model temperature to '25.5'" {
    send "Dummy/ask\r"
  }
  timeout {
    puts "Error: Did not receive expected output"
    exit 1
  }
}

expect {
  "25.5" {
    send "/set model temp default Dummy/ask\r"
  }
  timeout {
    puts "Error: Did not receive expected output"
    exit 1
  }
}

expect {
  "None" {
    send "/exit\r"
  }
  timeout {
    puts "Error: Did not receive expected output"
    exit 1
  }
}

expect {
  eof  {}
  timeout {
    puts "Error: Did not receive eof"
    exit 1
  }
}

exit 0

