#!/usr/bin/env expect-f.sh

# Set timeout for the expect script
set timeout 2

spawn aicli --model=dummy:dummy

expect {
  ">>> " { send "/echo Version is /version\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  -re {Version is \d+\.\d+\.\d+\+g} { send "/exit\r" }
  timeout { puts "Error: Did not receive input"; exit 1 }
}
expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}

spawn aicli --version

expect {
  -re {\d+\.\d+\.\d+\+g} { }
  timeout { puts "Error: Did not receive version"; exit 1 }
}

expect {
  eof {}
  timeout { puts "Error: Did not receive eof"; exit 1 }
}


exit 0
