#!/bin/sh

  # -DLLMODEL_CUDA=OFF \
cmake -B build \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DKOMPUTE_OPT_USE_BUILT_IN_VULKAN_HEADER=OFF \
  -DKOMPUTE_OPT_DISABLE_VULKAN_VERSION_CHECK=ON \
  -DKOMPUTE_OPT_USE_BUILT_IN_FMT=OFF \
  "$@"

